import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en" data-theme="light"
      className={`${geistSans.className} h-full antialiased`}
    >

      <body className="min-h-full flex flex-col">
        <header>
          <NavBar></NavBar>
        </header>
        
        {children}

      </body>
    </html>
  );
}
